// Code generated by raiden-cli; DO NOT EDIT.
package bootstrap

import (
	"github.com/sev-2/raiden/pkg/resource"
	"medpoint/internal/models"
)

func RegisterModels() {
	resource.RegisterModels(
		&models.Doctors{},
		&models.EPrescriptions{},
		&models.Faskes{},
		&models.FaskesAddress{},
		&models.Poli{},
		&models.Reservation{},
		&models.Schedules{},
		&models.Services{},
		&models.Transaction{},
		&models.Users{},
	)
}
