// Code generated by raiden-cli; DO NOT EDIT.
package bootstrap

import (
	"github.com/sev-2/raiden/pkg/resource"
	"medpoint/internal/types"
)

func RegisterTypes() {
	resource.RegisterTypes(
		&types.Doctors{},
		&types.EPrescriptions{},
		&types.Faskes{},
		&types.FaskesAddress{},
		&types.Poli{},
		&types.Reservation{},
		&types.ReservationStatusEnum{},
		&types.RoleEnum{},
		&types.Schedules{},
		&types.Services{},
		&types.Transaction{},
		&types.TransactionStatusEnum{},
		&types.Users{},
	)
}
